export const APP_ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  account: '/account',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  decks: '/decks',
  chunks: '/chunks',
  cards: '/cards',
  review: '/review',
  newDeck: '/decks/new',
  newCard: '/cards/new',
  newChunk: '/chunks/new',
  deckEdit: (id: string) => `/decks/${id}/edit`,
  deckCards: (id: string) => `/decks/${id}/cards`,
  deckChunks: (id: string) => `/decks/${id}/chunks`,
  cardEdit: (id: string) => `/cards/${id}/edit`,
  chunkEdit: (id: string) => `/chunks/${id}/edit`,
  resetPasswordWithToken: (token: string) =>
    `/reset-password?token=${encodeURIComponent(token)}`,
} as const;
